title: "JAMIE HWANG-BLACK"
author: false
description: "Portfolio Website" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "jamiehwangblack@gmail.com"
#twitter_username: "jamiehwangblack"
#github_username: "jamiehwangblack"
#linkedin_username: "jamiehwangblack"
#facebook_username: username
#flickr_username: username
#instagram_username: "jamiehwangblack"
#pinterest_username: username
#youtube_username: "jamiehwangblack"
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
